import type { NextPage } from 'next'
import Head from 'next/head'
import PromoList from '../components/PromoList'
import Masonry from '../components/Masonry'

import { mainArticle } from '../utils/data';

import styles from '../styles/Home.module.scss'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <PromoList />
      <Masonry data={mainArticle}/>
    </div>
  )
}

export default Home
